import { FeedbackItemType } from "./types";

export const MAX_CHARACTERS = 150;

export const exampleFeedbackItems: FeedbackItemType[] = [
  {
    id: 1,
    upvoteCount: 200,
    badgeInitials: "B",
    language: "Basque",
    text: "The #Basque word 'urdina' ('blue' in English) comes from the word for water, 'ur'.",
    daysAgo: 12,
  },
  {
    id: 2,
    upvoteCount: 165,
    badgeInitials: "E",
    language: "English",
    text: "The #English word 'bear' was originally a euphamism (meaning 'brown' or 'wild animal') that was used instead of the animal's, now lost, name.",
    daysAgo: 10,
  },
  {
    id: 3,
    upvoteCount: 133,
    badgeInitials: "S",
    language: "Spanish",
    text: "The #Spanish word 'izquierda' (left in English) comes from the Basque word of the same meaning 'ezkerra'.",
    daysAgo: 10,
  },
  {
    id: 4,
    upvoteCount: 85,
    badgeInitials: "W",
    language: "Welsh",
    text: "The #Welsh word 'Cymru' means 'friend' as opposed to the English word of the same meaning 'Wales' which means 'stranger' or 'outsider'.",
    daysAgo: 7,
  },
  {
    id: 5,
    upvoteCount: 83,
    badgeInitials: "C",
    language: "Cornish",
    text: "The #Cornish word for water 'dowr' and the Iberian River Duero have the same etymological root",
    daysAgo: 7,
  },
  {
    id: 6,
    upvoteCount: 70,
    badgeInitials: "S",
    language: "Swahili",
    text: "The #Swahili word for book 'kitabu' comes from the Arabic word for book 'kitab'.",
    daysAgo: 5,
  },
  {
    id: 7,
    upvoteCount: 64,
    badgeInitials: "W",
    language: "Welsh",
    text: "The #Welsh word for water 'dwr' and the Iberian River Duero have the same etymological root.",
    daysAgo: 4,
  },
  {
    id: 8,
    upvoteCount: 32,
    badgeInitials: "B",
    language: "Breton",
    text: "The #Breton word 'marh' (meaning 'horse') has the same root as the English word 'mare'.",
    daysAgo: 3,
  },
  {
    id: 9,
    upvoteCount: 26,
    badgeInitials: "W",
    language: "Welsh",
    text: "The #Welsh word 'Cymru' means 'friend' as opposed to the English word of the same meaning 'Wales' which means 'stranger' or 'outsider'.",
    daysAgo: 3,
  },
  {
    id: 10,
    upvoteCount: 20,
    badgeInitials: "W",
    language: "Welsh",
    text: "The #Welsh word 'Cymru' means 'friend' as opposed to the English word of the same meaning 'Wales' which means 'stranger' or 'outsider'.",
    daysAgo: 1,
  },
];
